ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.retail.ApplicationKt.module ]
    }
}

database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://db.ziqkxgsdjvtiijeonfpt.supabase.co:5432/postgres?ssl=true&sslmode=require"
    user = "retail_app_user"
    password = "RetailApp2026Password!"
}
