ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.retail.ApplicationKt.module ]
    }
}

database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?ssl=true&sslmode=require&prepareThreshold=0"
    url = ${?DB_URL}
    user = "postgres.nuqaqxkbrjkenbpmhgdt"
    user = ${?DB_USER}
    password = "Prodavalnik"
    password = ${?DB_PASSWORD}
}
